# Generated by Django 4.2.24 on 2025-09-26 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='trip_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='seat_no',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
